version: '3.5'

services:

  alfred_dyson_data_collector_service:
    build: .
    image: alfred_dyson_data_collector_service:latest
    container_name: alfred_dyson_data_collector_service
    restart: always
    hostname: alfred_dyson_data_collector_service
    networks:
      - alfred 
    
networks:

  alfred:
    name: nat
    driver: nat